### ISSUE TITLE
problems with addon my playlists and my muisc

### ISSUE THREAD

**Issue by bszafko** [Sharp-Frost/Deezer-KODI#1]
first of all thanks for your hard work it was really great to find this plugin for my favorite media center app.

I'm currently using deezer trial and wanted to see how it works with xbmc. I cloned it into addons dir,  restarted xbmc, configured credentials(i'm sure it's ok) however i get error whenever i access my music or my playlists. Error from xbmc.log ::
19:13:03 T:2858417008  NOTICE: Args:?mode=myMusic
19:13:03 T:2858417008  NOTICE: {'mode': 'myMusic'}
19:13:04 T:2858417008  NOTICE: -->Python Interpreter Initialized<--
19:13:04 T:2858417008  NOTICE: Args:?mode=myPlaylists
19:13:04 T:2858417008  NOTICE: {'mode': 'myPlaylists'}
19:13:04 T:2858417008  NOTICE: DeezerAPI.getMyPlaylists
19:13:04 T:2858417008   ERROR: Error Type: <type 'exceptions.AttributeError'>
19:13:04 T:2858417008   ERROR: Error Contents: 'module' object has no attribute 'Oauthexception'
19:13:04 T:2858417008   ERROR: Traceback (most recent call last):
                                              File "/home/bartek/.xbmc/addons/plugin.audio.deezer/deezer.py", line 117, in <module>
                                                deezerApi.getMyPlaylists()
                                              File "/home/bartek/.xbmc/addons/plugin.audio.deezer/DeezerAPI.py", line 91, in getMyPlaylists
                                                listResult =self.getRemoteData(base_url+'user/me/playlists')
                                              File "/home/bartek/.xbmc/addons/plugin.audio.deezer/DeezerAPI.py", line 39, in getRemoteData
                                                listResult =jsonDeserializer.decode(jsonResult)
                                              File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                                obj, end = self.scan_once(s, idx)
                                              File "/home/bartek/.xbmc/addons/plugin.audio.deezer/Json2Python.py", line 23, in dict_to_object
                                                class_ = getattr(module, class_name)
                                            AttributeError: 'module' object has no attribute 'Oauthexception'
19:13:04 T:3043084032   ERROR: GetDirectory - Error getting plugin://plugin.audio.deezer/?mode=myPlaylists
19:13:04 T:3043084032   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.deezer/?mode=myPlaylists) failed

**Comment by yolyolyolyol** [comment]
hello, i think i read everything about that, but sorry if i didn t found the answer...
so, i understood that this problem (30s issue) should be solved.
but i still have the error problem for "my playlists" and "my albums", AND for the exploration, i m still limited to 30s...
any idea?

thx! 
yol
